### ISSUE TITLE
Error with the unprojection script

### ISSUE THREAD

**Issue by cdapo** [NVlabs/imaginaire#70] opened 2021-04-27 13:49 UTC
Hi everyone,

I'm getting an error with the unprojection script. After generating the merged.ply file, I get the following error using "project_keypoints_cuda.py":
```
Importing ply file
Imported in 0.1836414337158203 seconds
Found 150949 points
  0%|                                                    | 0/10 [00:00<?, ?it/s]Transform took: 0.0032432079315185547

Traceback (most recent call last):
  File "project_keypoints_cuda.py", line 246, in <module>
    main(image_dir, sfm_dir, save_dir,
  File "project_keypoints_cuda.py", line 105, in main
    rgb = rgb_all[mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 150949
```
Changing the line 
```mask = p_c_all[:, 2] > 0``` to ```mask = True```  fixes this problem, but generates
```     
Traceback (most recent call last):
  File "project_keypoints_cuda.py", line 230, in <module>
    main(image_dir, sfm_dir, save_dir,
  File "project_keypoints_cuda.py", line 117, in main
    p_i_cuda, p_i_undist_cuda = project_many(cam, p_c)
  File "project_keypoints_cuda.py", line 42, in project_many
    points = points / points[:, 2:]
RuntimeError: The size of tensor a (150949) must match the size of tensor b (150947) at non-singleton dimension 1
``` 
in the project_many function

Any idea how to fix this?

**Comment by arunmallya** [comment] 2021-11-12 19:46
Hard to debug this without the specific data used, as the same script works fine for us. Closing the issue for now, can reopen if data is available.

**Closed by arunmallya** 2021-11-12 19:46 UTC

**Comment by siddharthbhushan** [comment] 2022-01-09 16:14
Hi,

I have been trying to run the unprojections script on some of my custom data. After generating .ply file, I keep running into the same error(the boolean index one). The problem in my case is that the ply_reader function returns rgb array of shape (0, 3) size. Shouldn't this be (abc, 3) where abc is the number of points in the point cloud? However, xyz returns an array of size (abc, 3). Is this happening with anyone else also? 

I tried using the berlin dataset that is used as an example on the OpenSfM blog and same problem persists with that dataset as well. Any idea what could be the cause of this, if at all this a problem?

**Comment by digvijayad** [comment] 2022-07-06 17:33
According to [issue here](https://github.com/isl-org/Open3D/issues/3100)

This reason for the error is that OpenSfM generates the `merged.ply` file with `diffuse_` headers for colors.
```
property uchar diffuse_red
property uchar diffuse_green
property uchar diffuse_blue
```
These are user-defined headers that are currently not supported by open3D, hence the empty `rbg_all`

The solution is to edit the `OpenSfM/opensfm/io.py` file and remove the diffuse_ from the properties in the function `point_cloud_to_ply`.

```
def point_cloud_to_ply(
    points: np.ndarray,
    normals: np.ndarray,
    colors: np.ndarray,
    labels: np.ndarray,
    fp: TextIO,
) -> None:
    fp.write("ply\n")
    ...
    ...
    fp.write("property uchar red\n")       # Changed from diffuse_red
    fp.write("property uchar green\n")     # Changed from diffuse_green
    fp.write("property uchar blue\n")      # Changed from diffuse_blue
    fp.write("property uchar class\n")
    fp.write("end_header\n")
```
The colors should be read correctly now if you regenerate the ply using OpenSfM.
